### ISSUE TITLE
Necesito una estrofa

### ISSUE THREAD

**Issue by ReneAguirre** [ReneAguirre/PercepcionN5Equipo9#2]
añadir una estrofa que contenga la palabra osos 
![f6bda3d44f94e2887791dbd3125232c1](https://user-images.githubusercontent.com/42328873/44490146-22a36580-a623-11e8-9919-f6f2c0f5fe97.jpg)

**Comment by gplaza1** [comment]
se ha agregado la estrofa sobre el oso
