### ISSUE TITLE
Necesito otra estrofa 

### ISSUE THREAD

**Issue by ReneAguirre** [ReneAguirre/PercepcionN5Equipo9#3]
agrega una estrofa que contenga la palabra gatos
![c64f0475196dc54f4dd4386ad962beba](https://user-images.githubusercontent.com/42328873/44562965-a8a5d600-a721-11e8-9f20-dcb28a3a3226.jpg)

**Comment by LuisEzp** [comment]
mis gatos vuelan por las noche,
mi luz es eterna,
un gato viene y te maulla,
eso te revela mi dulzura
